// =============================================================================
// SURGE BRK — Entry point / CLI runner
// Usage: npx ts-node src/run.ts --ticker BTCUSDT --tf 1h --trail LiqDraw
// =============================================================================

import { Backtest, walkForward } from "./metrics/backtest.js";
import { DEFAULT_BRK_CONFIG }    from "../types/index.js";
import type { BacktestConfig }   from "./metrics/backtest.js";
import type { OHLCV }            from "../types/index.js";

// ─── CCXT / Binance fetch helper ───────────────────────────────────────────────
// Replace with your data source. This expects Binance OHLCV format:
// [[timestamp, open, high, low, close, volume], ...]

export function parseBinanceOHLCV(raw: number[][]): OHLCV[] {
  return raw.map(r => ({
    ts:     r[0],
    open:   r[1],
    high:   r[2],
    low:    r[3],
    close:  r[4],
    volume: r[5],
  }));
}

// ─── Run backtest from CLI ─────────────────────────────────────────────────────

async function main() {
  const args   = process.argv.slice(2);
  const get    = (flag: string, def: string) => {
    const idx = args.indexOf(flag);
    return idx >= 0 ? args[idx + 1] : def;
  };

  const ticker    = get("--ticker", "BTCUSDT");
  const tf        = get("--tf",     "1h");
  const trail     = get("--trail",  "LiqDraw") as "ATR"|"Swing"|"LiqDraw"|"BEthenTrail";
  const lookback  = parseInt(get("--lookback", "20"));
  const capital   = parseFloat(get("--capital", "10000"));

  console.log(`\nSURGE BRK Backtest — ${ticker} ${tf} | Trail: ${trail}`);
  console.log("─".repeat(52));

  // ── Load data ────────────────────────────────────────────────────────────
  // In production: inject from CCXT or local DB
  // Example with CCXT:
  //   import ccxt from "ccxt";
  //   const exchange = new ccxt.binance();
  //   const raw = await exchange.fetchOHLCV(ticker, tf, undefined, 1000);
  //   const bars = parseBinanceOHLCV(raw);

  // For now: load from local JSON (generated by data pipeline)
  let bars: OHLCV[];
  try {
    const { readFileSync } = await import("fs");
    const dataPath = `./data/${ticker}_${tf}.json`;
    bars = JSON.parse(readFileSync(dataPath, "utf-8"));
    console.log(`Loaded ${bars.length} bars from ${dataPath}`);
  } catch {
    console.log("No local data found. Generating synthetic bars for demo...");
    bars = generateSyntheticBars(2000, ticker);
  }

  // ── Config ───────────────────────────────────────────────────────────────
  const config: BacktestConfig = {
    brkConfig: {
      ...DEFAULT_BRK_CONFIG,
      trailMode:      trail,
      rollingLookback: lookback,
    },
    initialCapital:  capital,
    riskPctPerTrade: 1.0,      // 1% equity per trade
    commissionPct:   0.05,     // Binance futures taker
    slippagePct:     0.02,
    maxConcurrent:   2,
    tf,
    ticker,
  };

  // ── Single-pass backtest ──────────────────────────────────────────────────
  const bt = new Backtest(config).run(bars);
  console.log(bt.summary);
  console.log("\nGrades:");
  for (const [key, g] of Object.entries(bt.grades)) {
    const bar = { A:"████", B:"███░", C:"██░░", F:"█░░░" }[g.grade] ?? "░░░░";
    console.log(`  ${g.label.padEnd(18)} ${String(g.value.toFixed(3)).padStart(8)}  ${bar} [${g.grade}]`);
  }

  // ── Walk-forward validation ────────────────────────────────────────────────
  console.log("\n── Walk-Forward (70/30, 3 windows) ──────────────────────────");
  const wf = walkForward(bars, config, { inSamplePct: 0.70, numWindows: 3 });
  console.log(`OOS Sharpe:    ${wf.oos.sharpe.toFixed(3)}`);
  console.log(`OOS Calmar:    ${wf.oos.calmar.toFixed(3)}`);
  console.log(`OOS PF:        ${wf.oos.profitFactor.toFixed(3)}`);
  console.log(`OOS MaxDD:     ${wf.oos.maxDrawdownPct.toFixed(1)}%`);
  console.log(`Strategy stable: ${wf.stable ? "✓ YES" : "✗ NO — possible overfit"}`);

  for (let w = 0; w < wf.windows.length; w++) {
    const win = wf.windows[w];
    console.log(`\n  Window ${w+1}: IS Sharpe ${win.inSample.metrics.sharpe.toFixed(2)}  →  OOS Sharpe ${win.outSample.metrics.sharpe.toFixed(2)}`);
    console.log(`           IS Trades ${win.inSample.metrics.totalTrades}   OOS Trades ${win.outSample.metrics.totalTrades}`);
  }
}

// ─── Synthetic bar generator (demo / CI testing) ──────────────────────────────
function generateSyntheticBars(n: number, ticker: string): OHLCV[] {
  let price   = ticker.includes("BTC") ? 45000 : 2500;
  const bars: OHLCV[] = [];
  const MS_1H = 3600_000;
  const start = Date.now() - n * MS_1H;

  for (let i = 0; i < n; i++) {
    const drift = (Math.random() - 0.495) * price * 0.003;
    const shock = Math.random() < 0.05 ? (Math.random() - 0.5) * price * 0.02 : 0;
    price       = Math.max(price * 0.5, price + drift + shock);

    const range  = price * (0.005 + Math.random() * 0.015);
    const open_  = price;
    const close_ = price + (Math.random() - 0.5) * range;
    const high_  = Math.max(open_, close_) + Math.random() * range * 0.3;
    const low_   = Math.min(open_, close_) - Math.random() * range * 0.3;

    bars.push({
      ts:     start + i * MS_1H,
      open:   open_,
      high:   high_,
      low:    low_,
      close:  close_,
      volume: 100 + Math.random() * 5000,
    });
  }
  return bars;
}

main().catch(console.error);
